version: '3'
services:

  edge-module:
    image: gbizconnect/gbizconnect-node-nginx:v0.0.1
    depends_on:
      - swaggerui
      - swaggereditor
    ports:
#      - 80:80
      - 443:443
    networks:
      - edge-network
    volumes:
      - ${PWD}/edge-module/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/edge-module/nginx/conf.d/edge-module.conf:/etc/nginx/conf.d/edge-module.conf
      - ${PWD}/edge-module/nginx/js/nginx.js:/etc/nginx/js/nginx.js
      - ${PWD}/edge-module/nginx/ssl/localhost.pem:/etc/nginx/ssl/localhost.pem
      - ${PWD}/edge-module/nginx/ssl/localhost.key:/etc/nginx/ssl/localhost.key
      - ${PWD}/edge-module/nginx/ssl/dh2048.pem:/etc/nginx/ssl/dh2048.pem
      - ${PWD}/edge-module/nginx/ssl/trusted_ca_cert.crt:/etc/nginx/ssl/trusted_ca_cert.crt
      - ${PWD}/edge-module/nginx/html:/usr/share/nginx/html
      - ${PWD}/edge-module/nginx/.htpasswd:/etc/nginx/.htpasswd
      - ${PWD}/edge-module/log:/var/log/nginx/
      - ${PWD}/permanent/config.json:/etc/nginx/resources/config.json

  swaggerui:
    image: swaggerapi/swagger-ui:v3.24.3
#    ports:
#      - 8080:8080
    networks:
      - edge-network
    volumes:
      - ${PWD}/swaggerui/swagger.json:/usr/share/nginx/html/swagger.json
    environment: 
      - API_URL=https://node.example.jp/swaggerui/swagger.json

  swaggereditor:
    image: swaggerapi/swagger-editor:v3.7.0
#    ports:
#      - 8080:8080
    networks:
      - edge-network
    volumes:
      - ${PWD}/swaggereditor/index.html:/usr/share/nginx/html/index.html

  jsonserver:
    image: clue/json-server:latest
    ports:
      - 80:80
    networks:
      - edge-network
    volumes:
      - ${PWD}/jsonserver/db.json:/data/db.json
      - ${PWD}/jsonserver/routes.json:/data/routes.json
    command: -r routes.json

  config-nginx-php:
    image: nginx:1.17.6
    depends_on:
      - config-php-script
    ports:
      - 8080:8080
    networks:
      - edge-network
    volumes:
      - ${PWD}/config-nginx-php/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/config-nginx-php/conf.d/config.conf:/etc/nginx/conf.d/config.conf

  config-php-script:
    image: php:7.4-rc-fpm-alpine3.10
#    ports:
#      - 9000:9000
    networks:
      - edge-network
    volumes:
      - ${PWD}/config-php-script/html/setting.php:/var/www/html/setting.php
      - ${PWD}/config-php-script/log/php_error.log:/var/www/html/log/php_error.log
      - ${PWD}/permanent/config.json:/var/www/html/resources/config.json
    working_dir: /var/www/myapp

  td-agent:
    image: gbizconnect/gbizconnect-node-td-agent:v0.0.1
    ports:
      - 24233:24233/tcp
    networks:
      - edge-network
    volumes:
      - ${PWD}/td-agent/edge/td-agent.conf:/etc/td-agent/td-agent.conf
      - ${PWD}/td-agent/setting:/var/log/setting
      - ${PWD}/td-agent/tmp:/var/log/td-agent/tmp
      - ${PWD}/edge-module/log:/var/log/nginx/
      - ${PWD}/config-php-script/log:/var/www/html/log
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /tmp
      - /run
    stop_signal: SIGRTMIN+3
    command: /sbin/init

networks:
  edge-network:
