version: '3'
services:

  edge-module:
    image: gbizconnect/gbizconnect-node-nginx:v1.0.4
    depends_on:
      - swaggerui
      - swaggereditor
    ports:
#      - 80:80
      - ${NODE_PORT}:443
    command: >
      /bin/sh -c
      "usermod -u ${gBizConnect_UID} nginx
      && groupmod -g ${gBizConnect_GID} nginx
      && envsubst '
      $$dummy
      '< /etc/nginx/conf.d/edge-module.conf.template
      > /etc/nginx/conf.d/edge-module.conf
      && envsubst '
      $$dns
      '< /etc/nginx/conf.d/resolver.conf.template
      > /etc/nginx/conf.d/resolver.conf
      && nginx -g 'daemon off;'"
    networks:
      - edge-network
    volumes:
      - ${PWD}/edge-module/nginx/conf.d/rate-limit.location.conf:/etc/nginx/conf.d/rate-limit.location.conf
      - ${PWD}/edge-module/nginx/conf.d/rate-limit.http.conf:/etc/nginx/conf.d/rate-limit.http.conf
      - ${PWD}/edge-module/nginx/conf.d/proxy-ssl-verify-depth.conf:/etc/nginx/conf.d/proxy-ssl-verify-depth.conf
      - ${PWD}/edge-module/nginx/conf.d/lua-ssl-verify-depth.conf:/etc/nginx/conf.d/lua-ssl-verify-depth.conf
      - ${PWD}/edge-module/nginx/conf.d/api.header.conf:/etc/nginx/conf.d/api.header.conf
      - ${PWD}/edge-module/nginx/ssl/server.crt:/etc/nginx/ssl/server.crt
      - ${PWD}/edge-module/nginx/ssl/private.key:/etc/nginx/ssl/private.key
      - ${PWD}/edge-module/nginx/.htpasswd:/etc/nginx/.htpasswd
      - ${PWD}/edge-module/log:/var/log/nginx/
      - ${PWD}/permanent/config.json:/etc/nginx/resources/config.json
    environment: 
      - dns=${dns}

  swaggerui:
    image: gbizconnect/gbizconnect-node-swaggerui:v1.0.4
#    ports:
#      - 8080:8080
    networks:
      - edge-network
    command: >
      /bin/sh -c
      "envsubst '
      $$NODE_DOMAIN
      $$NODE_PORT
      '< /usr/share/nginx/html/swagger.json.template
      > /usr/share/nginx/html/swagger.json
      && sh /docker-entrypoint.d/40-swagger-ui.sh
      && nginx -g 'daemon off;'"
    environment: 
      - SWAGGER_JSON_URL=https://${NODE_DOMAIN}/swaggerui/swagger.json
      - NODE_DOMAIN=${NODE_DOMAIN}
      - NODE_PORT=${NODE_PORT}

  swaggereditor:
    image: gbizconnect/gbizconnect-node-swaggereditor:v1.1.2
#    ports:
#      - 8081:8081
    networks:
      - edge-network
    command: >
      /bin/sh -c
      "envsubst '
      $$NODE_DOMAIN
      $$NODE_PORT
      '< /usr/share/nginx/html/index.html.template
      > /usr/share/nginx/html/index.html
      && sh /docker-entrypoint.sh nginx -g 'daemon off;'"
    environment:
      - NODE_DOMAIN=${NODE_DOMAIN}
      - NODE_PORT=${NODE_PORT}

  jsonserver:
    image: gbizconnect/gbizconnect-node-jsonserver:v1.0.3
    # ports:
      # - 80:80
    networks:
      - edge-network
    volumes:
      - ${PWD}/jsonserver/db.json:/data/db.json
      - ${PWD}/jsonserver/routes.json:/data/routes.json
    command: -r routes.json
    init: true

  config-nginx-php:
    image: gbizconnect/gbizconnect-node-config-nginx-php:v1.0.5
    depends_on:
      - config-php-script
    ports:
      - 8080:8080
    networks:
      - edge-network
    command: >
      /bin/sh -c
      "envsubst '
      $$dummy
      '< /etc/nginx/conf.d/config.conf.template
      > /etc/nginx/conf.d/config.conf
      && nginx -g 'daemon off;'"

  config-php-script:
    image: gbizconnect/gbizconnect-node-config-php-script:v1.0.5
#    ports:
#      - 9000:9000
    command: >
      /bin/sh -c
      "usermod -u ${gBizConnect_UID} www-data
      && groupmod -g ${gBizConnect_GID} www-data
      && php-fpm"
    networks:
      - edge-network
    volumes:
      - ${PWD}/config-php-script/log/php_error.log:/var/www/html/log/php_error.log
      - ${PWD}/permanent/config.json:/var/www/html/resources/config.json
    working_dir: /var/www/myapp

  td-agent:
    image: gbizconnect/gbizconnect-node-td-agent:v1.0.3
    ports:
      - 24224:24224/tcp
    user: "${gBizConnect_UID}:${gBizConnect_GID}"
    networks:
      - edge-network
    volumes:
      - ./td-agent/tmp:/var/log/td-agent/tmp
      - ./edge-module/log:/var/log/nginx/
      - ./config-php-script/log:/var/www/html/log
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tty: true
    stdin_open: true
    privileged: true
    tmpfs:
      - /tmp
      - /run
    stop_signal: SIGRTMIN+3
    init: true

networks:
  edge-network:
